type BetProps = { index: string; title: string; context: string; call: string; held: string; role: string; system: string; stage: string };
function ProjectArt({ index }: { index: string }) {
  const number = Number(index);
  return <div className={`project-art project-art-${number}`} aria-hidden="true"><span className="art-label">PROTO / SYSTEM {index}</span>
    {number === 1 && <div className="mini-app"><div className="mini-nav"><strong>daily /</strong><span>OVERVIEW　 SUBSCRIPTIONS　 OPERATIONS</span></div><div className="mini-welcome">A little less admin. A lot more momentum.</div><div className="mini-title">Your day, in perspective.</div><div className="mini-stats"><div>Active plans<strong>248<span style={{ fontSize: 8 }}> ↗</span></strong></div><div>Today&apos;s deliveries<strong>186</strong></div><div>Fulfilment<strong>98.4<small style={{ fontSize: 8 }}>%</small></strong></div></div><div className="mini-bars">{[35, 50, 42, 65, 60, 72, 57, 86, 76, 90, 84, 100].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div></div>}
    {number === 2 && <div className="mini-app"><div className="mini-nav"><strong>practice<span style={{ color: "#7a8e64", fontSize: 16 }}>✳</span></strong><span>YOUR SPACE TO GROW</span></div><div className="mini-title">Care, without the chaos.</div>{["Personalised nutrition", "Progress that stays visible", "Every client. One place."].map((text, i) => <div key={text} className="client-row"><i>{["↗", "◎", "+"][i]}</i><span>{text}</span><small>CONNECTED</small></div>)}</div>}
    {number === 3 && <div className="charging"><div className="charging-unit"><div className="charging-screen">ϟ</div><span>CONNECTED / 001</span></div><div className="charging-data"><p>ENERGY, WORKING HARDER.</p><strong>7.4<span style={{ fontSize: 15 }}> kW</span></strong><p>● CHARGING IN PROGRESS</p><div className="charge-line" /></div></div>}
    {number === 4 && <svg viewBox="0 0 420 220" className="vision-art" fill="none"><path d="M20 30h30M20 30v30M400 30h-30M400 30v30M20 195h30M20 195v-30M400 195h-30M400 195v-30" stroke="currentColor" opacity=".5" /><g stroke="currentColor" strokeWidth="1.2"><path d="m180 170-35-42-17-30 10-6 30 34-14-74 12-3 25 68-1-87 12-1 11 87 12-75 12 2-4 82 17-43 11 4-20 67-30 22Z" />{[[180,170],[145,128],[128,98],[168,126],[154,52],[191,117],[190,30],[213,116],[225,41],[233,123],[250,80],[211,175]].map(([cx,cy],i)=><circle key={i} cx={cx} cy={cy} r="3" fill="#dfac79" />)}<path d="M180 170l-12-44 23-9 22-1 20 7-22 52M145 128l23-2M191 117l-11 53M213 116l-2 59" opacity=".5" /></g><text x="35" y="180" fill="currentColor" fontSize="7" fontFamily="monospace">GESTURE RECOGNISED</text><text x="300" y="55" fill="currentColor" fontSize="7" fontFamily="monospace">● LIVE INPUT</text></svg>}
    {number === 5 && <div className="note-stack"><div /><div /><div><small>CAPTURE. CONNECT. REMEMBER.</small><p>A little less lost.<br />A little more learned.</p><i /><i style={{ width: "45%" }} /></div></div>}
    <span className="art-caption">CONCEPT VISUAL / {index}</span></div>;
}
export default function BetCard({ index, title, context, call, held, role, system, stage }: BetProps) {
  return <article className="work-card on-scroll"><ProjectArt index={index} /><div className="work-info"><div className="work-info-top"><span className="mono-label">{index} / {system}</span><span className="mono-label">{stage} ↗</span></div><h3>{title}</h3><details className="work-details"><summary>The thinking behind the build <span aria-hidden="true">+</span></summary><dl><dt className="mono-label">THE CONTEXT</dt><dd>{context}</dd><dt className="mono-label">THE CALL I MADE</dt><dd>{call}</dd><dt className="mono-label">WHY IT HELD</dt><dd>{held}</dd><dt className="mono-label">MY ROLE</dt><dd>{role}</dd></dl></details></div></article>;
}

